- name : PLAY-01
  hosts: catalogue
  tasks:
  - name : task 01 and play 01
    ansible.builtin.debug:
      msg: "Hello from Task 01 and play 01"
  - name : task 02 and play 01
    ansible.builtin.debug:
      msg: "Hello from Task 02 and play 01"
- name : PLAY-02
  hosts: catalogue
  tasks:
  - name : task 01 and play 02
    ansible.builtin.debug:
      msg: "Hello from Task 01 and play 02"
  - name : task 02 and play 02
    ansible.builtin.debug:
      msg: "Hello from Task 02 and play 02"