- name : play level variables
  hosts: local
  connection: local
  vars:
  - COURSE : DevOps
  - Trainer: Sivakumar
  tasks:
  - name : print the course info
    ansible.builtin.debug:
      msg: "Hey the course is {{COURSE}} and the trainer is {{Trainer}}"