- name : variables with prompt
  hosts: local
  connection: local
  tasks:
  - name : printing the variables from the arguments
    ansible.builtin.debug:
      msg : "Hey the course is {{COURSE}} and the trainer is {{Trainer}} and duration is {{Duration}}"

  # ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 -e "COURSE=Ansible" -e "DURATION=10HRS" -e "Trainer=Sivakumar" 09-vars-args.yaml