- name : variables with prompt
  hosts: local
  connection: local
  vars:
  - NAME : manisha from play 
  tasks:
  - name : vars preference
  vars:
  - NAME : manisha from task 
  vars_prompt:

    - name: name
      prompt: What is your username?
      private: false
  vars_files:
  - course.yaml

  tasks:
  - name : printing the variables from task level
    ansible.builtin.debug:
      msg : "Hey the name is  {{NAME}}"
