- name : variables with prompt
  hosts: local
  connection: local
  # vars:
  # - NAME : manisha from play 
  # vars_prompt:

  #   - name: NAME
  #     prompt: What is your name?
  #     private: false
  # vars_files:
  # - course.yaml
  tasks:
  - name : vars pfrom task lvel
    # vars:
    # - NAME : manisha from task 
    ansible.builtin.debug:
      msg : "Name : {{NAME}}"
