- name : using filters
  hosts: local
  connection: local
  vars:
  - fruits : mango
  tasks:
  - name : convert to upper case
    debug:
      # msg: "{{ fruits | upper() }}"
      msg : " Hello , the name is {{ name | default('manu') }}"
      
